# Data Lakehouse Time Travel com Apache Spark e Delta Lake

services:
  spark:
    build: .
    container_name: delta-lake-sil
    volumes:
      - ./delta:/repositorio
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
